spring.application.name=SpringBoot_Practice

spring.datasource.username = Srijon
spring.datasource.password = Srijon

spring.datasource.url = jdbc:h2:mem:testDB
spring.datasource.driverClassName = org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
